### ISSUE TITLE
problems with upgrading to strfun_type6

### ISSUE THREAD

**Issue by TomFD** [beltoforion/muparser#101]
Hi, 

let me firstly explain what was working:
I needed to define a function for later evaluation by:

```
m_mu_parser.DefineFun(std::wstring(_T("Ramp")), Ramp, false);
```

where my function is defined as

```
double Ramp(const wchar_t* s, double start, double end, double min, double max) ...
```

everything worked fine.
_However_, I needed to add one more parameter to my function, but there was no template for it.
So I created a new one in muParserDef.h, line 408
```
typedef value_type(*strfun_type6)(const char_type*, value_type, value_type, value_type, value_type, value_type);
```
and added code where strfun_type5 also had similar code, that was here:

muParserBase.cpp, line 1209:
```
case 5: Stack[sidx] = (*(strfun_type6)pTok->Fun.ptr)(m_vStringBuf[iIdxStack].c_str(), Stack[sidx], Stack[sidx + 1], Stack[sidx + 2], Stack[sidx + 3], Stack[sidx + 4]); continue;
```
muParserCallback.cpp, line 378:
```
	ParserCallback::ParserCallback(strfun_type6 a_pFun, bool a_bAllowOpti)
		:m_pFun((void*)a_pFun)
		, m_iArgc(5)
		, m_iPri(-1)
		, m_eOprtAsct(oaNONE)
		, m_iCode(cmFUNC_STR)
		, m_iType(tpSTR)
		, m_bAllowOpti(a_bAllowOpti)
	{} 
```
muParserCallback.h, line 85:
```
		ParserCallback(strfun_type6 a_pFun, bool a_bAllowOpti);
```
Now the problem: With this additional argument, evaluating a string like Ramp("M0",100,400,-1,2,1) catches a ParserError "String value used where a numerical argument is expected" with an iPos = 25.
I don't know what I missed. I can't see a String value.
What can I do? 

Thank you in advance.

**Comment by beltoforion** [comment]
Can't tell what you missed but i added string function with 5 parameters
