### ISSUE TITLE
Couldn't link to muparser library built without wide-character support.

### ISSUE THREAD

**Issue by MehdiChinoune** [beltoforion/muparser#103]
Building an application that depends on both muparser and Qt6 fails on Windows

the muparser library was built without UNICODE support while the Qt6 define UNICODE for compilation.
the application imports the unicode (string_type->wstring) because of the compilation definitions imposed by Qt6, and links with mupasrer which was built without unicde (string_type->string), That result to a lot of errors of `undefined reference`.

**Comment by beltoforion** [comment]
I'm sorry, this is a linking issue with a different application not under my control. I can't really help. My suggestion would be to try linking a muparser library build with unicode support

**Comment by MehdiChinoune** [comment]
> I'm sorry, this is a linking issue with a different application not under my control. I can't really help. My suggestion would be to try linking a muparser library build with unicode support

I don't have control on muparser packaging (It was packaged by vcpkg).
My demand is to make muparser compatible with both cases with/without unicode.

**Comment by beltoforion** [comment]
You have to compile muparser either with UNICODE support or without. You can't use both at the same time. This is not a parser related issue. I don't control how it is packaged or used in any distributions.

**Comment by MehdiChinoune** [comment]
Could you add a property to CMakeConfig file that could help CMake detect Unicode support.

**Comment by Osyotr** [comment]
Common approach to fix the issue is to have additional `W`-versions of functions.
When `ENABLE_WIDE_CHAR` is `OFF`, user gets `foo(char *)`.
When `ENABLE_WIDE_CHAR` is `ON`, user gets both `foo(char *)` and `foo_w(wchar *)`.

**Comment by beltoforion** [comment]
The parser is alreasy using the _UNICODE definition fo this. I won't change it.
