### ISSUE TITLE
any easy way make muparser accept armadillo mat type?

### ISSUE THREAD

**Issue by ShannonZ** [beltoforion/muparser#109]
Any way available to combine muparser with armadillo?

For example, a user typed model/function accept matrix and return results after some matrix operations.
http://arma.sourceforge.net/docs.html#Mat

`mat var_a = zeros(3,3);
		mu::Parser p;
		p.DefineVar(L"a", &var_a);
		p.DefineFun(L"MySqr", MySqr);
		p.SetExpr(L"1+a");
		std::cout << p.Eval() << std::endl;`

**Comment by beltoforion** [comment]
No
