### ISSUE TITLE
Issue with expression limit

### ISSUE THREAD

**Issue by Fabian188** [beltoforion/muparser#110]
On our software I upgraded muParser to 2.3.2 and now have issues with a testcase, where an expression of size 9488 is too long due to the new 5000 characters limit. 
The part which generates the long expression is not from me, it is a complex 3D tensor rotation formula. 

Is there a chance to exceed the 5000 limit or do we have to stick to the 2.2.6 version "forever"?
Is there a build time variable I can change?
Thanks!

**Comment by beltoforion** [comment]
There is no build time variable. You can extend the limit by changing the value of MaxLenExpression in muParserDef.h You can try checking out the trunk version. I have doubled the limit to 10000.

How long is your expression?

There is no technical reason for this limit other than that a long expression string is more likely to be an attack on the parsing engine than a real expression.

**Comment by Fabian188** [comment]
Thanks for the response, that helps.

We had this issue with two testcases, one had 9k and the other 27k characters.
At least for the last I assume this is not intended and we shall investigate if this is necessary. 
For the time being 2.2.6 is fine for us and there is no urge.

**Comment by beltoforion** [comment]
The limit is actually at 20000. I'll see haw that goes. Maybe i'll bump it to 30k. The sole purpose of the limit is to protect me from bug reports coming from oss-fuzz related to 50k expressions. Internally there is no hard limitation. This is just a spam filter.

**Comment by Fabian188** [comment]
We shall get rid of our long expression. Do you know how to convert it to a dot file such that we can visualize it via graphviz dot to analyze it?

**Comment by beltoforion** [comment]
Sorry, can't help you with that.
