### ISSUE TITLE
Lack of Visual Studio project compiling with Ev3

### ISSUE THREAD

**Issue by jmanthony3** [beltoforion/muparser#113]
I am trying to compile a Visual Studio project that requires symbolic differentiation in C++ wherein the parser is instantiated with a string expression. I have tried compiling _muParser_ as either a static or shared library with and without the fix to the `muParserFixes.h` header file in #105 in conjunction with the [Ev3 library](https://github.com/openturns/ev3) compiled to either a static or shared library. The proposed fix does allow me to compile the muParser code and evaluate string expressions in the `mu::` namespace, but does not aid in the effort to compile the Ev3 code with similar attempts to compile to either static or shared libraries.

What am I missing?

![image](https://user-images.githubusercontent.com/62029937/175368132-02c9f96b-35bb-4a82-b95a-a8738586a185.png)[Error messages when attempting to compile with Ev3 library.]

![image](https://user-images.githubusercontent.com/62029937/175370994-ee6a7593-412d-48b7-822a-d554c923ccf7.png)[Successful evaluation in `mu::` namespace for muParser.]

Here is my Visual Studio info...

Microsoft Visual Studio Community 2022
Version 17.2.4
VisualStudio.17.Release/17.2.4+32602.215
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA747
Microsoft Visual C++ 2022

ASP.NET and Web Tools 2019   17.2.392.13739
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.2.392.13739
Azure App Service Tools v3.0.0

C# Tools   4.2.0-4.22281.5+8d3180e5f00d42f0f0295165f756f368f0cbfa44
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.22089.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Linux Core Dump Debugging   1.0.9.32408
Enables debugging of Linux core dumps.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.2.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Python - Django support   17.0.22089.1
Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.22089.1
Profiling support for Python projects.

Python - VC Project Support   17.0.21344.1
Provides support for launching C++ projects with Python debugging enabled.

Python with Pylance   17.0.22089.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.10418.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.2.0-4.22281.5+8d3180e5f00d42f0f0295165f756f368f0cbfa44
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.32408
Visual C++ for Linux Development

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**Comment by beltoforion** [comment]
Ok I understand. I'll leave the ticket open but your chance to find help may be grater at the Ev3 project page. My ability to support ends with the muparser namespace. 

@jschueller Can you help out here?

**Comment by jmanthony3** [comment]
Thank for clarifying this @jschueller. I have successfully built and implemented Ev3 into my project and it works as advertised.

Why would the cmake allow for a *Debug* build if this is not actually supported?
