### ISSUE TITLE
constants not doucmented

### ISSUE THREAD

**Issue by ManuelSchneid3r** [beltoforion/muparser#118]
Hi, 
I use your lib (thank you by the way) in albertlauncher/albert. I link your [documentation](https://beltoforion.de/en/muparser/features.php) from the app for users. I noticed that the constants are not documented. It would be nice if you could document the constants _e ,_pi, etc (maybe some i dont know) in the online docs. 

By the way is there a reason why they are prefixed with an underscore?

**Comment by beltoforion** [comment]
Sure I can add the constants. The reason for using the underscore in constant names is lost to history.

**Comment by ManuelSchneid3r** [comment]
> lost to history.

i dont get that. not a native speaker, sorry. can you please rephrase?

**Comment by beltoforion** [comment]
No problem. It means that I have no recollection or documentation that explains why i choose to use the underscore in the variable name. Probably to mark it as a constant that is built in.

**Comment by ManuelSchneid3r** [comment]
Can we remap the names? E.g. from _pi to pi. Or do you mind to change these generally?

**Comment by beltoforion** [comment]
Probably not because that is how they are named for a long time and a lot of people will start complaining if i change them. You can however define your own constants.

**Comment by beltoforion** [comment]
Documentation updated
