### ISSUE TITLE
Feature request: Add rnd() built-in function to generate random numbers

### ISSUE THREAD

**Issue by jmespadero** [beltoforion/muparser#124]
I am quite curious about why the [Built-in functions](https://beltoforion.de/en/muparser/features.php#idDef1) is so complete but does not include a rnd() o random() function to generate numbers in the  0.0..1.0 interval.

I know rnd() can be included as a user function, but why not include it for non-programmers user?

If you are interested but busy, tell here and I can proposse a Pull-Request.

**Comment by beltoforion** [comment]
You are the first one to ask for a random function. If you wanna add it as rnd returning a random value between 0 and 1 I will merge it.
