### ISSUE TITLE
Update cmake minimum required version

### ISSUE THREAD

**Issue by felix2010** [beltoforion/muparser#127]
When I build the library with a recent `cmake` (3.27), i get the following warning
```
CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```
The required version by this projet is very old (3.1) and compatibility with an actual `cmake` is no longer guaranteed as stated in the [cmake documentation](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#policy-settings).

Thus I would ask to requiring a more recent `cmake`.

Bumping the required `cmake` version to 3.15 gives no deprecation- or policy warnings, but having 3.15 at least could help simplify the handling of compiler warning flags as described by [CMP0092](https://cmake.org/cmake/help/latest/policy/CMP0092.html#cmp0092).

**Comment by beltoforion** [comment]
I have set it to 3.15.
