### ISSUE TITLE
Using period in a variable.name

### ISSUE THREAD

**Issue by ishovkun** [beltoforion/muparser#128]
Is there any way to use a period "." in a variable name? 

I am trying to define a variable as follows:
```
mu::Parser parser;
double value;
parser.DefineVar("inputs.poro", &value);

``` 
and I'm getting the following exception:
Invalid function-, variable- or constant name: "".

**Comment by beltoforion** [comment]
Try adding it to the characters allowed in variable names like described here:
https://beltoforion.de/en/muparser/interface.php#idDefCharset

**Comment by ishovkun** [comment]
It worked! Thank you!
