### ISSUE TITLE
Feature request: static library on Ubuntu

### ISSUE THREAD

**Issue by MarcoFilimon** [beltoforion/muparser#129]
Hello! Not sure if this is actually a feature request or a problem I have, but any help is appreciated.

I want to use this library by linking it static. My project is cross platform , Windows and Ubuntu. 
On Windows I managed to build the project and have as an output both the dynamic and static libraries with the following CMake commands:

1) cmake -B build_win64\CMake -A "x64"
2) cmake --build build_win64\CMake --config RelWithDebInfo --parallel --verbose -- /p:CL_MPcount=%NUMBER_OF_PROCESSORS%

On Ubuntu the same (almost) commands, only build the dynamic library. I tried to set BUILD_SHARED_LIBS both on OFF and ON but no difference. Any idea how can I generate the static library in this case?

Thanks!

**Comment by beltoforion** [comment]
Gotta say no to this one. I have no plans for maintaining the distribution of a static library. The dynamic libraries are already part of many distributions. I won't increase the maintainance burden on this project.
