### ISSUE TITLE
SetExpr & GetExpr

### ISSUE THREAD

**Issue by TomFD** [beltoforion/muparser#130]
Hi, is it necessary that muparser uses the extra space _T(" ") added to the formula? Especially, the GetExpr will give this longer string back, which is not the original one I set.
I suggest that GetExpr should crop it again.
I had troubles with it, because I needed to get the expression out, manipulate it and set it again, but in a loop this string was getting longer and longer filled with spaces at the end.
Thank you,
Tom

**Comment by beltoforion** [comment]
Yes it was necessary once but probably not any more. If i remember correclty it had to do with bugs in some C++ compilers. I think i can remove it.

**Comment by beltoforion** [comment]
Issue closed; It remains necessary.
