### ISSUE TITLE
Pointer casting mismatch in muParserTest.h

### ISSUE THREAD

**Issue by mabraham** [beltoforion/muparser#142]
In several methods, e.g.
https://github.com/beltoforion/muparser/blob/master/include/muParserTest.h#L208

some pointer is cast to `std::intptr_t` before being returned as `value_type`, which as far as I can see is `double`. That looks risky. MSVC warns about the particular case of `FunUd0` which casts a `void*` to `std::intptr_t` and then returns as `value_type` like

```
[104/1186 83.0/sec] Building CXX object _deps\muparser-build\CMakeFiles\muparser.dir\src\muParserTest.cpp.obj
..\src\external\muparser\include\muParserTest.h(210): warning C4244: 'return': conversion from 'intptr_t' to 'mu::value_type', possible loss of data
```

This is a minor problem for GROMACS, which bundles muParser, and would like to have a warning-free build with MSVC. How should we fix this? Can we avoid building source files that include this header, if it's only used in tests of muParser?

**Comment by beltoforion** [comment]
This is just test code you can safely omit it from compilation.
