### ISSUE TITLE
C++ 20 standard support.

### ISSUE THREAD

**Issue by MarcoFilimonE** [beltoforion/muparser#147]
Hello!
Is there any chance to add support for C++ 20 standard?

**Comment by beltoforion** [comment]
Do you have any indication that it does not compile on a C++20 compliant compiler? What part of the code is not C++20 compliant?

**Comment by MarcoFilimonE** [comment]
We're using the conan2 package from: https://conan.io/center/recipes/muparser
We've just upgraded our conan profile to cpp 20 and now the build of the package is failing.

![image](https://github.com/user-attachments/assets/e6deee27-4613-4e73-aabd-f7b03f398d85)

**Comment by beltoforion** [comment]
I cannot find anything suspicious in the line referenced in the error message and i can compile Version 2.3.4 with Visual Studio.

**Comment by MarcoFilimonE** [comment]
Which version are you using?

**Comment by beltoforion** [comment]
VS2022; I opened the folder and build it with CMake

**Comment by MarcoFilimonE** [comment]
Ok, thanks for the information. Might be a problem with the Conan package, then. Are you the one who maintains it?

**Comment by beltoforion** [comment]
No I'm not the maintainer. Is there an easy way to reproduce the issue?

**Comment by MarcoFilimonE** [comment]
If I download your latest realese's source code and I change the CMake from
`set(CMAKE_CXX_STANDARD 11)`
to
`set(CMAKE_CXX_STANDARD 20)`

and then I run
1) cmake -G "Visual Studio 16 2019" -A x64 -B build/
2) cmake --build build/ --config RelWithDebInfo --parallel --verbose -- /p:CL_MPcount=%NUMBER_OF_PROCESSORS%

I get:

![image](https://github.com/user-attachments/assets/1ebb5da6-ca51-4637-a114-d06cd391679e)

**Comment by beltoforion** [comment]
Thats something i can work with. This has nothing to do with C++20. For some reason min and max are defined as macros. If you put #undef min and #undef max at the top of the file it should build. I will look for a more elegant solution that that today evening.

**Comment by beltoforion** [comment]
As far as i can tell the issue should be fixed. I will prepare a new service release 2.3.5 soon.
