### ISSUE TITLE
Please make a reference for the API and predefined constants

### ISSUE THREAD

**Issue by ManuelSchneid3r** [beltoforion/muparser#18]
There seems to be _pi and _e defined. Where can I find other constants? Also I would like to change the notation of the output, since 1000001 gives 1e+06. I have no need to save place in my app so the precise output would be fine, but I cant find an option to set.

**Comment by beltoforion** [comment]
http://muparser.beltoforion.de/

**Comment by ManuelSchneid3r** [comment]
I cleaned up in the post- _pi and _e are defined. But they do not appear here http://beltoforion.de/article.php?a=muparser&hl=en&p=features&s=idDef1#idDef1
