### ISSUE TITLE
Bug for variable and postfix 

### ISSUE THREAD

**Issue by simonyhchen** [beltoforion/muparser#19]
Dear developer,

If I define "k" as postfix (*1e3), and parsing this kind of equation.

"a+k+3k" --> it will be error ParserTokenReader::IsVarTok
I found this is cause by 'noVal' flag and can be fixed by change the order of IsPostFix to the presence of isVarTok.

How do you think??

**Comment by giraldeau** [comment]
I don't understand what the problem is. The correct expression would be `a+k+3*k`. Please reopen this issue if your problem is not solved. Thanks!
