### ISSUE TITLE
mod operator support

### ISSUE THREAD

**Issue by dilawar** [beltoforion/muparser#20]
I see that in the source code operator  `%` (mod) seems to be available, but not in the documentation http://muparser.beltoforion.de/mup_features.html . Indeed, I am getting a invalid parser state when I use `%`. 

Do you plan to include `%` in future release?

**Comment by Crayder** [comment]
Yeah I also tried using the modulus operator, it'd be great feature.

**Comment by beltoforion** [comment]
I can't add every conveivable operator by default. I'll leave the mod operator to the client code. There is no consensus about syntax and the "%" might be needed for a percentage operator in another context.
