### ISSUE TITLE
`-std=C++11` is must to compile the library?

### ISSUE THREAD

**Issue by dilawar** [beltoforion/muparser#23]
I noticed that `weak_ptr/unique_ptr` are used  `ParserTokenReader::Clone(ParserBase *a_pParent) const`. Does it mean the compiler has to support `c++11` or `c++0x` etc to compile the library. 

Is yes, which version can be used with a compiler which only has `c++98` support? We wish to support `CentOS-5` in our application, which has only gcc4.1 by default (I know its pretty old). 

Probably a good idea to mention it in the documentation.

**Comment by beltoforion** [comment]
Yes C++11 is required. I understand your dilemma but unfortunately i don't have the time to support outdated versions of the C++ standard. I could not find any hint in the release notes when the switch took place but i wouldn't recommend using an old version with known bugs anyway. I'm sorry but i can't help you.

**Comment by dilawar** [comment]
I was able to compile the library without `-std=c++11`. There is only couple of place where `weak_ptr/unique_ptr` is used, and converting them to raw pointers wasn't much work. If you want, I can send a pull request or a patch.

**Comment by beltoforion** [comment]
Thanks for the offer but phasing out C++98 support was a conscious decision to simplify the maintainance.
