### ISSUE TITLE
log() function returns natural logarithm

### ISSUE THREAD

**Issue by Wanup0** [beltoforion/muparser#24]
Hello,
As described in http://beltoforion.de/article.php?a=muparser&hl=en&p=features&s=idDef2#idDef2, built-in function log() returns logarithm to the base 10.
When running example1, log() returns natural logarithm:

>   Version 2.2.5 (20150427; GC; 64BIT; RELEASE; ASCII)
> ##   (C) 2015 Ingo Berg
> 
> Running test suite:
> 
> testing name restriction enforcement...passed
> testing syntax engine...passed
> testing postfix operators...passed
> testing infix operators...passed
> testing variable/constant detection...passed
> testing multiarg functions...passed
> testing expression samples...passed
> testing if-then-else operator...passed
> testing member functions...passed
> testing binary operators...passed
> testing error codes...passed
> testing string arguments...passed
> testing bulkmode...passed
> ## Test passed (542 expressions)
> 
> Commands:
> 
>   list var     - list parser variables
>   list exprvar - list expression variables
>   list const   - list all numeric parser constants
>   opt on       - enable optimizer (default)
>   opt off      - disable optimizer
>   locale de    - switch to german locale
>   locale en    - switch to english locale
>   locale reset - reset locale
>   test bulk    - test bulk mode
>   quit         - exits the parser
> 
> Constants:
> 
>   "_e"   2.718281828459045235360287
> ##   "_pi"  3.141592653589793238462643
> 
> Enter an expression or a command:
> log(10)
> ans=2.30258509299
> ln(10)
> ans=2.30258509299
> log10(10)
> ans=1
> ^C

G++ version:

> Using built-in specs.
> COLLECT_GCC=g++
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
> Target: x86_64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
> Thread model: posix
> gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 

Best regards,

Wanup0

**Comment by cesss** [comment]
The documentation page you mention shows the list of supported functions, and there are three functions for logarithms: log2(), log10() and log(). From the function names, it's obvious log10() is expected to be base 10 logarithms, while log() is expected to be natural logarithms, so the bug is in the documentation rather than the behavior, IMHO.

**Comment by Wanup0** [comment]
Sorry, I've just realized that this thread title is incomplete. I meant there was a difference between the behavior of log() function and it description in the documentation. I am agree with you. Clearly, it's a documentation mistake.

**Comment by giraldeau** [comment]
The [build-in function documentation](http://beltoforion.de/article.php?a=muparser&hl=en&p=features&s=idDef2#idDef2) is now explicit about the behavior of log(), log2(), log10(), and ln(). Thanks!
