### ISSUE TITLE
2.2.5 libs issue

### ISSUE THREAD

**Issue by rosset** [beltoforion/muparser#25]
v2.2.5 provides these libs:
   /usr/lib64/libmuparser.so
   /usr/lib64/libmuparser.so.2
   /usr/lib64/libmuparser.so.2.2.4 (shold be 2.2.5 instead?!?)
   /usr/lib64/pkgconfig/muparser.pc

v2.2.3 provides these libs:
   /usr/lib64/libmuparser.so
   /usr/lib64/libmuparser.so.2
   /usr/lib64/libmuparser.so.2.2.3
   /usr/lib64/pkgconfig/muparser.pc

**Comment by giraldeau** [comment]
This issue should be fixed with the CMake build system. Please report any other problem you might have. Thanks!
