### ISSUE TITLE
Replace auto_ptr with unique_ptr

### ISSUE THREAD

**Issue by Reputeless** [beltoforion/muparser#29]
`std::auto_ptr` is deprecated and removed in C++17.

**Comment by alonso12** [comment]
Compile warings when compiling with mingw gcc/c++.

"std::auto" is depreciated and should be replaced with "std::unique". 

muParserToken.h
about line 72
      //*** ***
      //std::auto_ptr<ParserCallback> m_pCallback;
      std::unique_ptr<ParserCallback> m_pCallback;
      //*** ***

muParserBase.h
about line 292
    //*** ***
    //std::auto_ptr<token_reader_type> m_pTokenReader; ///< Managed pointer to the token reader object.
    std::unique_ptr<token_reader_type> m_pTokenReader; ///< Managed pointer to the token reader object.
    //*** ***
