### ISSUE TITLE
Build muparser example2 with Visual Studio 2015 does not work

### ISSUE THREAD

**Issue by zhaofeng-shu33** [beltoforion/muparser#30]
Running nmake with VS140 toolset produces the file example2.exe, which works.
Running msbuild with VS140 toolset to build vcxproj (which is produced by VS120 toolset produces the file example2.exe, which crashes when user inputs something like "list var".

**Comment by zhaofeng-shu33** [comment]
As far as I know, unicode supported multi-language console app can not properly run on a specific code page. However, even if I chcp 65001, example2.exe still crashes when I type "list var". The crashing code is at
function  mupGetVar muParserDLL.cpp(line 798 szName[sizeof(szName)-1] = 0). With VS debugger, I notice that szName[1024*4-1]=0. System exception throws and the app crashes.
In VS, strip "Using Unicode Charset" compiler option produces workable dll and example2.
Possibly there is some bugs in the original code when handling unicode characters？

**Comment by beltoforion** [comment]
closed; vs build system has been retired in favor of cmake

**Comment by zhaofeng-shu33** [comment]
OK
