### ISSUE TITLE
-no-cpp-precomp flag is not recognized on non-Apple gcc versions

### ISSUE THREAD

**Issue by kencu** [beltoforion/muparser#33]
Originally the configure script assumed that if the compiler was gcc and the system was darwin, then it would be Apple's gcc and the `-no-cpp-precomp` flag was used. This assumption is no longer true - other versions of gcc are used on darwin now, to get more modern compilers - but these FSF gcc versions error on the `-no-cpp-precomp` flag.

See <https://gcc.gnu.org/ml/gcc/2005-12/msg00367.html>. 

I think the darwin test in the gcc block could be deleted, as the `-no-cpp-precomp` flag does not appear to do anything since gcc3.x according to the link. I changed the block in the configure script to:

```
        DEPS_TRACKING=1

        if test "x$GCC" = "xyes"; then
            DEPSMODE=gcc
            DEPSFLAG="-MMD"
            { $as_echo "$as_me:${as_lineno-$LINENO}: result: gcc" >&5
$as_echo "gcc" >&6; }
```

and it no longer causes errors when compiled with newer non-Apple gcc versions.

**Comment by giraldeau** [comment]
This issue should be solved using the CMake build system. Please report any issue you may have. 
Thanks!
