### ISSUE TITLE
Enable travis-ci

### ISSUE THREAD

**Issue by giraldeau** [beltoforion/muparser#36]
The .travis-ci.yml is part of the directory and is working correctly: https://travis-ci.org/giraldeau/muparser

Let's enable that for the upstream project to ensure we don't break anything when merging stuff.

**Comment by jschueller** [comment]
@giraldeau do you have admin rights to enable travis ?

**Comment by giraldeau** [comment]
I don't, but @beltoforion has, and he was looking into it.

**Comment by jschueller** [comment]
Ok. An appveyor script would be great too to test windows builds.

**Comment by giraldeau** [comment]
Indeed, would it be easy for you to prepare that file? Unfortunately, I don't know Appveyor. Thanks!

**Comment by Croydon** [comment]
AppVeyor seems to be enable now. Travis is still missing.
