### ISSUE TITLE
Add eval function returning a string

### ISSUE THREAD

**Issue by ManuelSchneid3r** [beltoforion/muparser#44]
Are you calulating with floats internally? It would be cool to have a eval function that evaluates "0.8*0.8" to "0.64" instead of the float 0,6400000000000001.

**Comment by jschueller** [comment]
there's no symbolic caculus whasoever

**Comment by beltoforion** [comment]
Yes, muparser is calculating with double precision float values internally. If i understand you correctly you would like a version with fixed-point-arithmetics. Unfortunately that won't happen since it would require using a third party fixed-point-library thus adding a dependency to the parser.
