### ISSUE TITLE
Dual result of 'the same' expression

### ISSUE THREAD

**Issue by Darkriser** [beltoforion/muparser#45]
Let's have an expression 'max(0/0,1)' and mathematically equal
expression 'max(1,0/0)'. I expect (why shouldn't I ?) to get the same results.
However, muParser calculates
max(0/0,1) = -nan(ind)
max(1,0/0) = 1
max(1,0/0,1) = 1

Verified using the latest commit from Jan 23 2018 (6cf2746)
and an older version 2.2.4 (more than 2yrs old).
Is there a bug or my expectations are incorrect?

Thanks in advance,
Marcel

**Comment by beltoforion** [comment]
That is a bug, your expectations are fine. The result should probably be NaN in both cases since the NaN is  tainting the result.

**Comment by Darkriser** [comment]
I noticed that muParser uses std::max and std::min functions internally.
So I verified their behavior using a plain C++ code and received the same results.
I'll ask about this on some C++ devel forums, muParser seems to be above suspicion...

**Comment by beltoforion** [comment]
closed; If the behavior of std::max is the reason there is nothing i can do.
