### ISSUE TITLE
Dont want to throw exception incase of an error in an expression

### ISSUE THREAD

**Issue by anirban1710** [beltoforion/muparser#53]
Suppose i have a composed expression a=10 , b=20 + c , d = 30, e= 40 where the 2nd expression(b=20 +c) is erroneous. In this case, muParser will correctly throw exception and not evaluate 3rd and 4th expression. But i dont want to throw exception in the middle and want that the 3rd and 4th expression gets calculated. 
How can i achieve this ?

**Comment by beltoforion** [comment]
Try using custom preprocessing. Parse each expression in sequence.

**Comment by beltoforion** [comment]
Closed; worksfor me
