### ISSUE TITLE
some error  when  I make ?

### ISSUE THREAD

**Issue by JonyUnbroken** [beltoforion/muparser#56]
jony@jony-unbroken:~/3rd_party_lib/muparser$ make
/home/jony/3rd_party_lib/muparser/bk-deps g++ -c -o muParser_dll_muParser.o -DNDEBUG -DMUPARSER_DLL -DMUPARSERLIB_EXPORTS -I./include -fPIC -DPIC  -O2  ./src/muParser.cpp
In file included from ./include/muParserStack.h:34:0,
                 from ./include/muParserBase.h:39,
                 from ./include/muParser.h:32,
                 from ./src/muParser.cpp:26:
./include/muParserError.h:110:57: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
     ParserErrorMsg& operator=(const ParserErrorMsg &) = delete;
                                                         ^
./include/muParserError.h:111:45: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
     ParserErrorMsg(const ParserErrorMsg&) = delete;
                                             ^
./include/muParserError.h:114:24: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
    ~ParserErrorMsg() = default;
                        ^
In file included from ./include/muParserStack.h:35:0,
                 from ./include/muParserBase.h:39,
                 from ./include/muParser.h:32,
                 from ./src/muParser.cpp:26:
./include/muParserToken.h:72:12: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
       std::unique_ptr<ParserCallback> m_pCallback;
            ^
./include/muParserToken.h: In constructor ‘mu::ParserToken<TBase, TString>::ParserToken()’:
./include/muParserToken.h:91:10: error: class ‘mu::ParserToken<TBase, TString>’ does not have any field named ‘m_pCallback’
         ,m_pCallback()
          ^
./include/muParserToken.h: In member function ‘void mu::ParserToken<TBase, TString>::Assign(const mu::ParserToken<TBase, TString>&)’:
./include/muParserToken.h:135:9: error: ‘m_pCallback’ was not declared in this scope
         m_pCallback.reset(a_Tok.m_pCallback.get() ? a_Tok.m_pCallback->Clone()
         ^
./include/muParserToken.h: In member function ‘mu::ParserToken<TBase, TString>& mu::ParserToken<TBase, TString>::Set(const mu::ParserCallback&, const TString&)’:
./include/muParserToken.h:174:9: error: ‘m_pCallback’ was not declared in this scope
         m_pCallback.reset(new ParserCallback(a_pCallback));
         ^
./include/muParserToken.h: In member function ‘mu::ParserToken<TBase, TString>& mu::ParserToken<TBase, TString>::SetVal(TBase, const TString&)’:
./include/muParserToken.h:197:9: error: ‘m_pCallback’ was not declared in this scope
         m_pCallback.reset(0);
         ^
./include/muParserToken.h: In member function ‘mu::ParserToken<TBase, TString>& mu::ParserToken<TBase, TString>::SetVar(TBase*, const TString&)’:
./include/muParserToken.h:215:9: error: ‘m_pCallback’ was not declared in this scope
         m_pCallback.reset(0);
         ^
./include/muParserToken.h: In member function ‘mu::ParserToken<TBase, TString>& mu::ParserToken<TBase, TString>::SetString(const TString&, std::size_t)’:
./include/muParserToken.h:233:9: error: ‘m_pCallback’ was not declared in this scope
         m_pCallback.reset(0);
         ^
./include/muParserToken.h: In member function ‘mu::ECmdCode mu::ParserToken<TBase, TString>::GetCode() const’:
./include/muParserToken.h:276:13: error: ‘m_pCallback’ was not declared in this scope
         if (m_pCallback.get())
             ^
./include/muParserToken.h: In member function ‘mu::ETypeCode mu::ParserToken<TBase, TString>::GetType() const’:
./include/muParserToken.h:289:13: error: ‘m_pCallback’ was not declared in this scope
         if (m_pCallback.get())
             ^
./include/muParserToken.h: In member function ‘int mu::ParserToken<TBase, TString>::GetPri() const’:
./include/muParserToken.h:302:15: error: ‘m_pCallback’ was not declared in this scope
         if ( !m_pCallback.get())
               ^
./include/muParserToken.h:305:14: error: ‘m_pCallback’ was not declared in this scope
         if ( m_pCallback->GetCode()!=cmOPRT_BIN && m_pCallback->GetCode()!=cmO
              ^
./include/muParserToken.h:308:16: error: ‘m_pCallback’ was not declared in this scope
         return m_pCallback->GetPri();
                ^
./include/muParserToken.h: In member function ‘mu::EOprtAssociativity mu::ParserToken<TBase, TString>::GetAssociativity() const’:
./include/muParserToken.h:314:13: error: ‘m_pCallback’ was not declared in this scope
         if (m_pCallback.get()==NULL || m_pCallback->GetCode()!=cmOPRT_BIN)
             ^
./include/muParserToken.h:317:16: error: ‘m_pCallback’ was not declared in this scope
         return m_pCallback->GetAssociativity();
                ^
./include/muParserToken.h: In member function ‘mu::value_type (* mu::ParserToken<TBase, TString>::GetFuncAddr() const)()’:
./include/muParserToken.h:337:17: error: ‘m_pCallback’ was not declared in this scope
         return (m_pCallback.get()) ? (generic_fun_type)m_pCallback->GetAddr() 
                 ^
./include/muParserToken.h: In member function ‘int mu::ParserToken<TBase, TString>::GetArgCount() const’:
./include/muParserToken.h:379:14: error: ‘m_pCallback’ was not declared in this scope
         if (!m_pCallback->GetAddr())
              ^
./include/muParserToken.h:382:16: error: ‘m_pCallback’ was not declared in this scope
         return m_pCallback->GetArgc();
                ^
In file included from ./include/muParser.h:32:0,
                 from ./src/muParser.cpp:26:
./include/muParserBase.h: At global scope:
./include/muParserBase.h:291:10: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
     std::unique_ptr<token_reader_type> m_pTokenReader; ///< Managed pointer to
          ^
Makefile:332: recipe for target 'muParser_dll_muParser.o' failed
make: *** [muParser_dll_muParser.o] Error 1

**Comment by beltoforion** [comment]
Where is the makefile coming from? Did you run cmake first? Please try:

<pre>
cmake CMakeLists.txt
make clean all
</pre>

This works for me. Which compiler version did you use?

**Comment by JonyUnbroken** [comment]
thank you. It`s work.

**Comment by beltoforion** [comment]
Ok
