### ISSUE TITLE
muparser.beltoforion.de website is offline

### ISSUE THREAD

**Issue by smokris** [beltoforion/muparser#57]
This repo links to http://muparser.beltoforion.de, but that website is offline.

beltoforion.de specifies the following nameservers:

    docks19.rzone.de
    shades17.rzone.de

…but those nameservers return neither an `A` nor `CNAME` record for the muparser.beltoforion.de domain.

Is the domain permanently offline (and should the links thus be changed), or is this a temporary issue?

**Comment by beltoforion** [comment]
subdomains have been restored; fixed

**Comment by smokris** [comment]
Great. Thanks.
