### ISSUE TITLE
-std=c++11 was not added for Ubunto subsystem in Windows 10

### ISSUE THREAD

**Issue by mkhaled87** [beltoforion/muparser#58]
Hi,

I am using the library on Ubuntu-subsystem on Windows 10.
I have g++ 5.4.0.
After "./configure", and when doing a "make" i get the error:

`/include/muParserToken.h:72:12: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type`

After checking, the compile command, it seems missing "-std=c++11".
After adding it manually to the Makefile, the library compiles smoothly !

Regards,

**Comment by jschueller** [comment]
now only cmake is supported (c++11, symbols export) autools-like support should be removed
