### ISSUE TITLE
Compile error with #define MUP_BASETYPE float

### ISSUE THREAD

**Issue by francesco-cattoglio** [beltoforion/muparser#61]
I tried compiling the library using floats instead of doubles. I changed the corresponding line inside muParserDef.h to `#define MUP_BASETYPE float` but there were some compilation errors related to muParserDLL.h
To fix those, I also had to to change line 50 of muParserDLL.h to be
`typedef float muFloat_t`

I might have missed something while reading library documentation, but if the user is expected to make this little extra change maybe we could write something inside the Compiler switches web page, in the MUP_BASETYPE section.

**Comment by beltoforion** [comment]
The dll wasn't realy ever intended to be used with anything but double.  It would create a dll with the same name but an incompatible API. The muparser class itself is tested for other float types. The dll interface is just a wrapper for the class hardcoded at using double values.
