### ISSUE TITLE
64-bit compatibility issue in muParserBase.h

### ISSUE THREAD

**Issue by VioletGiraffe** [beltoforion/muparser#62]
```
 void  Error(EErrorCodes a_iErrc, 
                int a_iPos = (int)mu::string_type::npos, // <--- This line doesn't look safe
                const string_type &a_strTok = string_type() ) const;
```
`std::string::npos` is `size_type`, it's a 64-bit value in 64-bit mode. The highlighted line truncates it to 32-bit signed `int`. It's probably not causing any actual runtime errors, but looks bad and causes a host of compiler warnings (remember, it's in .h file so a warning is emitted for every .cpp that includes it).

**Comment by giraldeau** [comment]
I registered the project in my account, but there is no automatic trigger. 

https://ci.appveyor.com/project/giraldeau/muparser

**Comment by beltoforion** [comment]
Sorry, I have no idea what appveyyor is or does. Never used it before. 
@jschueller i have added you as a collaborator so if you want to set it up feel free to do it.

**Comment by jschueller** [comment]
Great, I could enable Appveyor, see the new README.rst.
It seems I need admin rights on the repo too to enable Travis though.

**Comment by jschueller** [comment]
@VioletGiraffe what of msvc version did you use ? any special flags ?

**Comment by VioletGiraffe** [comment]
@jschueller: msvc 2017 (v141 toolset), `/W4` flag.

**Comment by beltoforion** [comment]
@jschueller: giving admin rights does not seem to be so easy. Seems i need to create a new organization and transfer project ownership. (Something i would do if everything else fails)

I connected muparser to travis-ci can you access it there?

**Comment by jschueller** [comment]
Travis works properly, thanks.
Now I realize AppVeyor was only enabled on my fork and does not trigger builds from here. Could you do the same for AppVeyor ?

**Comment by beltoforion** [comment]
I added it to appveyor. Please check out if you see it.
