### ISSUE TITLE
Check parsing error without evaluation

### ISSUE THREAD

**Issue by chacha21** [beltoforion/muparser#64]
Would it be possible to add a check function that would raise up basic syntax errors without trying to evaluate the whole expression ? This would be helpful to detect basic problems without having to set up the whole context (variable could have any value, or even not being declared, as long as the tokens are at least well formed)

**Comment by beltoforion** [comment]
The function GetUsedVar is already doing this. It will parse the expression and return a list of variables in the expression. The variables do not have to be defined. Errors should be passed on as exceptions.

**Comment by chacha21** [comment]
Good, I did not find that in the documentation.
Just a suggestion (even if it might be pretty artifical regarding the muparser code), but what about considering the following API :
-SetExpr() doesn't perform any parsing work
-Parse() (an alias of GetUsedVar() that would not return anyhing but errors) offers basic error checking
-IsParsed() informs that a Parse() has already been done on the current expression
-EVal() performs evaluation, and of course triggers initial parsing only if needed in case Parse() hasn't been called previously. And of course errors can still be raised for invalid variables.

It may not change much in the muparser code, but it can help the user optimizing his own code when planning to reuse a muparser for a set of different expressions.

**Comment by beltoforion** [comment]
A change like this is not backwards compatible. I do not plan to modify the API in that manner. The muparser API is stable and the project is essentially in a maintainance phase with new features or additions being unlikely. 

For this reason I'm closing the issue.
