### ISSUE TITLE
Build problems with MSVC 2017

### ISSUE THREAD

**Issue by retiredracer** [beltoforion/muparser#67]
I pulled v 2.2.6.1 and tried to build the 'debug static' and 'release static' versions.

Two problems with the MSVC 'muparser.sln' configurations:

1) The 'Code Generation | Smaller Type Check' property is Yes, which causes the '/RTCc' option to be used on the compiler.  This inhibits the muparser build.  Lots of '/RTCc rejects conformant code' errors.

2) The 'MUPARSER_STATIC' preprocessor directive is missing which causes lots of 'dll-specification' errors - again, when compiling the 'static' configurations.  Needed to add this preprocessor directive to those build configurations.

**Comment by TomFD** [comment]
Still an issue. But adding the MUPARSER_STATIC in the preprocessor solved (2). Solution for (1) is also correct.
Thanks.

**Comment by beltoforion** [comment]
Visual studio is now capable of working with cmake. Unfortunately maintaining different build systems is not feasible. Therefore sln files have been removed from the current version.  Visual Studio is still the main development environment for me so all i can say is that it actually works with cmake.

The recommended and least painfull way to use the library is to add the source code directly to a project.
