### ISSUE TITLE
Version tag v2.2.6 instead of v2.2.6.1 

### ISSUE THREAD

**Issue by stefan-gavranovic** [beltoforion/muparser#82]
I believe that something went wrong when tagging a release. 
I noticed  version tag v2.2.6.1 for a release 2.2.6. This creates issues with existing conan recipes  that use that particular version. It tries to access github link `.../muparser/archive/v2.2.6.zip` which of course does not exist.  
Would you be willing to change the tag?

**Comment by beltoforion** [comment]
I don't think it would be a good idea to rename the tag. I have no idea what would happen to the release tied to it.

**Comment by stefan-gavranovic** [comment]
Thanks for your reply. I guess instead of renaming tag one would need to create a new one and update the release page. 
Otherwise I will just adapt my conan recipes.
