### ISSUE TITLE
Warning C4310

### ISSUE THREAD

**Issue by chacha21** [beltoforion/muparser#83]
If you want to cleanup some more warnings, there is this one with MSVC 2019 :

`muparser-master\include\muParserBase.h(182,74): warning C4310: cast truncates constant value`

for the line
`void Error(EErrorCodes a_iErrc, int a_iPos = (int)mu::string_type::npos, const string_type& a_strTok = string_type()) const;`

It is revealed at /W4 and fixed by a `static_cast<int>`

**Comment by beltoforion** [comment]
I wish i could... 

This would require me to change the signature of the function, this in turn will break the ABI which is potentially more dangerous than the truncation. The truncation itself does not really matter inside muparser.

**Comment by chacha21** [comment]
I do not suggest to replace `int a_iPos`, but rather `(int)mu::string::npos` by `static_cast<int>(mu::string::npos).` This would be exactly the same code, without a signature change. It just gets rid of the warning.

**Comment by beltoforion** [comment]
Ok, seems reasonable.
