### ISSUE TITLE
Exception thrown on 32 digits binary number (ParserInt)

### ISSUE THREAD

**Issue by jgeudens** [beltoforion/muparser#86]
Hi,

I have encountered an issue with the example of recognizing binary numbers (IsBinVal) in the ParserInt example. A binary number which consists of 32 digits is valid (maximum unsigned integer value), but an exception is thrown on this value. 31 digits is the maximum allowed at the moment. The offset of the '#' character isn't used in the check for the overflow.

**Comment by beltoforion** [comment]
I'll investigate it.
