### ISSUE TITLE
Is it possible to get prebuilt `.dll`s?

### ISSUE THREAD

**Issue by JonathanILevi** [beltoforion/muparser#87]
I am using MUParser in a project of mine, it has provided a much faster alternative to a serious bottleneck I had.

My project is in D, and I just generated some simple bindings to the C interface; it has been working well: https://code.dlang.org/packages/muparser-bindings

I am now trying to build my app for Windows, and, well, it is not as simple as Linux to get libraries installed, and being that I am using D bindings, I do not already have C build tools installed.

I would find prebuilt Windows libraries super beneficial.  Thanks,

**Comment by beltoforion** [comment]
Unfortunately I do not provide precompiled dll's because there are too many variants. (32 bit/64; CLang/VS; Debug/release). This has become unmaintainable. 

However I have placed a 64 bit dll compiled with VS2019 here:
https://beltoforion.de/en/muparser/muparser.dll

**Comment by JonathanILevi** [comment]
Sorry, thank you for that!

**Comment by beltoforion** [comment]
Nothing to be sorry for, let me know if you need a 32 bit dll.
