### ISSUE TITLE
Postfix operator with numbers

### ISSUE THREAD

**Issue by tonka3000** [beltoforion/muparser#96]
Hey,

it seems that a postfix operator with a number is not possible. I try to model `2cm2`, but I always get an error. `2cm` works great 😄 .

Is there any way to get this working in muparser?

muparser: 2.2.6.1

Greetings
Michael

**Comment by beltoforion** [comment]
I guess it's technically possible by adding numbers to the operator character set using DefineOprtChars. This will also allow them in binary operators which will introduce some parsing ambiguities when actually used in binary operators.

**Comment by tonka3000** [comment]
Thanks for your answer, it works 😄
